name: several_social_logins
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-142.0.dev <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.19
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.0
  kakao_flutter_sdk_user: ^1.1.1
  provider: ^6.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - .env
