// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFxnzo741pb_JHtscO6K045BifsM_Gm8U',
    appId: '1:389367182374:web:7ce2a7233958bf9a5022e7',
    messagingSenderId: '389367182374',
    projectId: 'logins-5a9ef',
    authDomain: 'logins-5a9ef.firebaseapp.com',
    storageBucket: 'logins-5a9ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3b92mn-9DZnJo6NJLoumcIipepD5K9LI',
    appId: '1:389367182374:android:7ba4b7ef4ddf4d065022e7',
    messagingSenderId: '389367182374',
    projectId: 'logins-5a9ef',
    storageBucket: 'logins-5a9ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWzAu4TWuSU6YZfDD1XmXpze-dZScThHI',
    appId: '1:389367182374:ios:fbde895a227b6ab65022e7',
    messagingSenderId: '389367182374',
    projectId: 'logins-5a9ef',
    storageBucket: 'logins-5a9ef.appspot.com',
    iosClientId: '389367182374-hc37hblc2o9adbiq9sfukndhi6lnor8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.severalSocialLogins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWzAu4TWuSU6YZfDD1XmXpze-dZScThHI',
    appId: '1:389367182374:ios:fbde895a227b6ab65022e7',
    messagingSenderId: '389367182374',
    projectId: 'logins-5a9ef',
    storageBucket: 'logins-5a9ef.appspot.com',
    iosClientId: '389367182374-hc37hblc2o9adbiq9sfukndhi6lnor8n.apps.googleusercontent.com',
    iosBundleId: 'com.example.severalSocialLogins',
  );
}
